name: Java CI Team-2

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag linkshortener:$(date +%s)
